################################################################################
#  File: buildspecs/secretsanalysis-buildspec.yml
#  Description: Buildspec for the Secrets Analysis CodeBuild project.
#  Author: Haitam Bidiouane (@sch0penheimer)
#  Last Modified: 14/09/2025
#
#  Purpose: This buildspec is designed to set up a CodeBuild project that scans
#           a specified CodeConnection-based Git Repository for hardcoded secrets using git-secrets.
################################################################################

version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    commands:
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')]: Install Phase begun."
      - echo "Updating package lists:"
      - apt-get update
      - echo "Installing system packages:"
      - apt-get -y install jq python3-pip python3-dev
      - echo "Installing/Upgrading the AWS CLI:"
      - pip3 install --upgrade awscli
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')]: Installation phase completed successfully."
    finally:
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')]: Cleanup of the install phase (always runs)."

  pre_build:
    commands:
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')]: Pre-build Phase. Setting up CodeConnections environment"
      - echo "Git CodeConnection ARN: $GIT_CODECONNECTION_ARN"
      - echo "Git Provider Type: $GIT_PROVIDER_TYPE"
      - echo "Git Repository ID: $GIT_REPOSITORY_ID"
      - echo "Branch: $CODE_BRANCH_NAME"
      - echo "Region: $AWS_DEFAULT_REGION"
      - echo "\n"
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')]: Pre-build Phase. Setting git-secrets in the CodeBuild src dir"
      - echo "Working Directory: $CODEBUILD_SRC_DIR"

  build:
    commands:
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')]: Build Launch."
      - git clone https://github.com/awslabs/git-secrets
      - cd git-secrets
      - make install
      - cd $CODEBUILD_SRC_DIR

      #- NOTE: With CodeConnections, the source code is available in $CODEBUILD_SRC_DIR -#
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')]: Source code available via CodeConnections"
      - ls -lrt
      
      #- Install git-secrets for this repository -#
      - git secrets --install
      - git secrets --register-aws

      #- Custom patterns -#
      - git secrets --add 'password\s*=\s*.+'
      - git secrets --add 'secret\s*=\s*.+'
      - git secrets --add 'api[_-]?key\s*=\s*.+'
      
      #- Scan for secrets -#
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')]: Scanning for hardcoded secrets begun."
      - git secrets --scan --recursive
      
  post_build:
    commands:
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')]: Build Completed. Secrets Scanning completed successfully."

artifacts:
  type: zip
  files: '**/*'