################################################################################
#  File: buildspecs/3-clair-sca-staging-buildspec.yml
#  Description: Buildspec for the Clair SCA + Staging CodeBuild project.
#  Author: Haitam Bidiouane (@sch0penheimer)
#  Last Modified: 14/09/2025
#
#  Purpose: 
#    This buildspec performs image vulnerability scanning (SCA) using Amazon ECR's built-in
#    integration with Clair to identify security issues in container images before deploying
#    them to the staging environment in ECS via the same buildspec project.
################################################################################

version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] Install Phase begun."
      - echo "Updating package lists:"
      - apt-get update
      - echo "Installing system packages:"
      - apt-get -y install jq python3-pip python3-dev
      - echo "Installing/Upgrading the AWS CLI:"
      - pip3 install --upgrade awscli
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] Installation Phase completed successfully."

  pre_build:
    commands:
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] Pre-build phase started."
      - echo "Starting Docker Daemon:"
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] Docker daemon ready."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] Pre-build Phase completed successfully."

  build:
    commands:
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] Build phase started."
      #- Wait for ECR's Clair scan to complete -#
      - |
        stat="IN_PROGRESS"
        while [ "$stat" != "COMPLETE" ]; do
          if [ "$stat" = "FAILED" ] || [ "$stat" = "CANCELLED" ]; then
            echo "ECR scan failed"
            exit 1
          fi
          stat=$(aws ecr describe-image-scan-findings --repository-name $ECR_REPO_NAME --image-id imageTag=$TAG | jq -r '.imageScanStatus.status')
          sleep 5
        done
      - aws ecr describe-image-scan-findings --repository-name $ECR_REPO_NAME --image-id imageTag=$TAG > ecr_scan_result.json
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] Build Phase completed successfully."

  post_build:
    commands:
      - |
        jq "{ \"eventType\": \"DevSecOps_Report\", \
        \"pipelineReportType\": \"ECR\", \
        \"generatedAt\": $(date +\"%Y-%m-%dT%H:%M:%S.%3NZ\"), \
        \"buildId\": env.CODEBUILD_BUILD_ID, \
        \"sourceRepository\": env.CODEBUILD_SOURCE_REPO_URL, \
        \"sourceBranch\": env.CODEBUILD_SOURCE_VERSION, \
        \"reportContent\": . }" ecr_scan_result.json > payload.json
      
      - |
        if [ $(grep -E 'HIGH|CRITICAL' ecr_scan_result.json) ]; then
          aws lambda invoke --function-name $LAMBDA_FUNCTION_NAME --payload file://payload.json ecr_scan_result.json && echo "LAMBDA_SUCCEEDED" || echo "LAMBDA_FAILED"
          echo "There are critical or high vulnerabilities.. failing the build"
          exit 1
        elif [ $(grep -E 'MEDIUM' ecr_scan_result.json) ]; then
          aws lambda invoke --function-name $LAMBDA_FUNCTION_NAME --payload file://payload.json ecr_scan_result.json && echo "LAMBDA_SUCCEEDED" || echo "LAMBDA_FAILED"
        fi
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] Deploying to ECS:"
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
      
      ##-- Wait for deployment to stabilize --##
      - echo "Waiting for service "$ECS_SERVICE_NAME" to reach steady state:"
      - aws ecs wait services-stable --cluster $ECS_CLUSTER_NAME --services $ECS_SERVICE_NAME
      
      ##-- Verify service is running and healthy -##
      - |
        RUNNING_COUNT=$(aws ecs describe-services --cluster $ECS_CLUSTER_NAME --services $ECS_SERVICE_NAME --query 'services[0].runningCount')
        if [ "$RUNNING_COUNT" -eq 0 ]; then
          echo "Service failed to start. Checking events..."
          aws ecs describe-services --cluster $ECS_CLUSTER_NAME --services $ECS_SERVICE_NAME --query 'services[0].events[0:5]'
          exit 1
        fi
      
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] Service deployed successfully"
      - echo "[$(date '+%Y-%m-%d %H:%M:%S')] Generating imagedefinitions.json for CodeDeploy ECS deployment:"
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_SERVICE_NAME $ECR_REPO_URI:$TAG > imagedefinitions.json
      - echo "[$(date '+%Y-%m-%d %H:%M:%S")] Post-build phase completed successfully."

artifacts:
  type: zip
  files:
    - imagedefinitions.json
    - ecr_scan_result.json
    - payload.json